"""sync_user_members_rbac_and_system_settings

Revision ID: 207a6cc09ec3
Revises: e4fda818a508
Create Date: 2026-09-06 23:29:15.092359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '207a6cc09ec3'
down_revision: Union[str, Sequence[str], None] = 'e4fda818a508'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_system_settings_updated_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_system_settings'))
    )
    op.create_index(op.f('ix_system_settings_key'), 'system_settings', ['key'], unique=True)
    op.alter_column('registrations', 'consent_given',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('registrations', 'consent_timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    op.add_column('users', sa.Column('member_id', sa.UUID(), nullable=True))
    op.add_column('users', sa.Column('is_superadmin', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.create_index(op.f('ix_users_member_id'), 'users', ['member_id'], unique=False)
    op.create_foreign_key(op.f('fk_users_member_id_members'), 'users', 'members', ['member_id'], ['id'], ondelete='SET NULL')
    op.sync_enum_values(
        enum_schema='public',
        enum_name='role_enum',
        new_values=['Ketua', 'Wakil Ketua', 'Sekretaris', 'Bendahara', 'Kepala Divisi', 'Staff', 'Anggota'],
        affected_columns=[TableReference(table_schema='public', table_name='members', column_name='role')],
        enum_values_to_rename=[],
    )

    # Sinkronisasi data awal: Hubungkan users.member_id ke members.id dan perbarui is_superadmin & role
    op.execute("""
        UPDATE users u
        SET member_id = m.id,
            role = m.role::text,
            division = m.division
        FROM members m
        WHERE u.student_id = m.student_id;
    """)

    # Tandai Superadmin (Dzulfikri Adjmal / NIM 2210511084)
    op.execute("""
        UPDATE users
        SET is_superadmin = true
        WHERE student_id = '2210511084';
    """)

    # Seed default intake setting jika belum ada
    op.execute("""
        INSERT INTO system_settings (id, key, value, description, updated_at)
        VALUES (
            '0191c981-8000-7000-8000-000000000001',
            'intake_config',
            '{"status": "OPEN", "batch_name": "Penerimaan Anggota Baru Periode 2026", "deadline": "2026-08-31", "quota": 100}',
            'Pengaturan Periode Penerimaan Calon Anggota KSM AIoT',
            NOW()
        )
        ON CONFLICT (key) DO NOTHING;
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='role_enum',
        new_values=['Ketua', 'Wakil Ketua', 'Kepala Divisi', 'Staff', 'Anggota'],
        affected_columns=[TableReference(table_schema='public', table_name='members', column_name='role')],
        enum_values_to_rename=[],
    )
    op.drop_constraint(op.f('fk_users_member_id_members'), 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_member_id'), table_name='users')
    op.drop_column('users', 'is_superadmin')
    op.drop_column('users', 'member_id')
    op.alter_column('registrations', 'consent_timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('registrations', 'consent_given',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.drop_index(op.f('ix_system_settings_key'), table_name='system_settings')
    op.drop_table('system_settings')
    # ### end Alembic commands ###
