"""initial_schema_with_enums

Revision ID: 208840aa062f
Revises: 
Create Date: 2026-08-30 21:55:09.722228

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '208840aa062f'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('Accepted', 'Pending', 'Rejected', name='selection_status_enum').create(op.get_bind())
    sa.Enum('Aktif', 'Tidak Aktif', 'Alumni', name='member_status_enum').create(op.get_bind())
    sa.Enum('IoT Embedded', 'AI', 'Software Engineer & Cloud', name='research_field_enum').create(op.get_bind())
    sa.Enum('Ketua', 'Wakil Ketua', 'Kepala Divisi', 'Staff', 'Anggota', name='role_enum').create(op.get_bind())
    sa.Enum('BPH', 'Akademik Riset', 'PSDM', 'Humas Multimedia', name='division_enum').create(op.get_bind())
    sa.Enum('S1 Informatika', 'S1 Sistem Informasi', 'S1 Sains Data', 'D3 Sistem Informasi', name='study_program_enum').create(op.get_bind())

    # Data normalization before altering columns
    op.execute("""
        UPDATE users
        SET division = CASE
            WHEN division ILIKE '%Akademik%' OR division ILIKE '%Riset%' THEN 'Akademik Riset'
            WHEN division ILIKE '%PSDM%' OR division ILIKE '%Sumber Daya%' OR division ILIKE '%Pengembangan%' THEN 'PSDM'
            WHEN division ILIKE '%Humas%' OR division ILIKE '%Multimedia%' THEN 'Humas Multimedia'
            ELSE 'BPH'
        END;
    """)

    op.execute("""
        UPDATE members
        SET division = CASE
            WHEN division ILIKE '%Akademik%' OR division ILIKE '%Riset%' THEN 'Akademik Riset'
            WHEN division ILIKE '%PSDM%' OR division ILIKE '%Sumber Daya%' OR division ILIKE '%Pengembangan%' THEN 'PSDM'
            WHEN division ILIKE '%Humas%' OR division ILIKE '%Multimedia%' THEN 'Humas Multimedia'
            ELSE 'BPH'
        END;
    """)

    op.execute("""
        UPDATE members
        SET role = CASE
            WHEN role ILIKE '%Ketua%' AND role NOT ILIKE '%Wakil%' THEN 'Ketua'
            WHEN role ILIKE '%Wakil%' THEN 'Wakil Ketua'
            WHEN role ILIKE '%Kepala%' OR role ILIKE '%Kadiv%' OR role ILIKE '%Koordinator%' THEN 'Kepala Divisi'
            WHEN role ILIKE '%Staff%' OR role ILIKE '%Staf%' THEN 'Staff'
            ELSE 'Anggota'
        END;
    """)

    op.execute("""
        UPDATE members
        SET status = CASE
            WHEN status ILIKE '%Alumni%' THEN 'Alumni'
            WHEN status ILIKE '%Tidak%' OR status ILIKE '%Nonaktif%' THEN 'Tidak Aktif'
            ELSE 'Aktif'
        END;
    """)

    op.execute("""
        UPDATE members
        SET program_of_study = CASE
            WHEN program_of_study ILIKE '%Sains Data%' THEN 'S1 Sains Data'
            WHEN program_of_study ILIKE '%D3%' THEN 'D3 Sistem Informasi'
            WHEN program_of_study ILIKE '%Sistem Informasi%' THEN 'S1 Sistem Informasi'
            ELSE 'S1 Informatika'
        END;
    """)

    op.execute("""
        UPDATE registrations
        SET program_of_study = CASE
            WHEN program_of_study ILIKE '%Sains Data%' THEN 'S1 Sains Data'
            WHEN program_of_study ILIKE '%D3%' THEN 'D3 Sistem Informasi'
            WHEN program_of_study ILIKE '%Sistem Informasi%' THEN 'S1 Sistem Informasi'
            ELSE 'S1 Informatika'
        END;
    """)

    op.execute("""
        UPDATE registrations
        SET status = CASE
            WHEN status ILIKE '%APPROV%' OR status ILIKE '%Accept%' THEN 'Accepted'
            WHEN status ILIKE '%REJECT%' THEN 'Rejected'
            ELSE 'Pending'
        END;
    """)

    op.alter_column('members', 'program_of_study',
               existing_type=sa.VARCHAR(length=100),
               type_=postgresql.ENUM('S1 Informatika', 'S1 Sistem Informasi', 'S1 Sains Data', 'D3 Sistem Informasi', name='study_program_enum'),
               existing_nullable=False,
               postgresql_using='program_of_study::study_program_enum')
    op.alter_column('members', 'division',
               existing_type=sa.VARCHAR(length=100),
               type_=postgresql.ENUM('BPH', 'Akademik Riset', 'PSDM', 'Humas Multimedia', name='division_enum'),
               existing_nullable=False,
               postgresql_using='division::division_enum')
    op.alter_column('members', 'role',
               existing_type=sa.VARCHAR(length=100),
               type_=postgresql.ENUM('Ketua', 'Wakil Ketua', 'Kepala Divisi', 'Staff', 'Anggota', name='role_enum'),
               existing_nullable=False,
               postgresql_using='role::role_enum')
    op.alter_column('members', 'interest_track',
               existing_type=sa.VARCHAR(length=255),
               type_=postgresql.ARRAY(postgresql.ENUM('IoT Embedded', 'AI', 'Software Engineer & Cloud', name='research_field_enum')),
               existing_nullable=True,
               postgresql_using="""CASE
                   WHEN interest_track IS NULL THEN NULL
                   WHEN interest_track ILIKE '%IoT%' OR interest_track ILIKE '%Embedded%' OR interest_track ILIKE '%Hardware%' THEN ARRAY['IoT Embedded'::research_field_enum]
                   WHEN interest_track ILIKE '%Software%' OR interest_track ILIKE '%Cloud%' OR interest_track ILIKE '%Web%' THEN ARRAY['Software Engineer & Cloud'::research_field_enum]
                   ELSE ARRAY['AI'::research_field_enum]
               END""")
    op.alter_column('members', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=postgresql.ENUM('Aktif', 'Tidak Aktif', 'Alumni', name='member_status_enum'),
               nullable=False,
               postgresql_using='status::member_status_enum')
    op.alter_column('registrations', 'program_of_study',
               existing_type=sa.VARCHAR(length=100),
               type_=postgresql.ENUM('S1 Informatika', 'S1 Sistem Informasi', 'S1 Sains Data', 'D3 Sistem Informasi', name='study_program_enum'),
               existing_nullable=False,
               postgresql_using='program_of_study::study_program_enum')
    op.alter_column('registrations', 'interest_track',
               existing_type=sa.VARCHAR(length=100),
               type_=postgresql.ARRAY(postgresql.ENUM('IoT Embedded', 'AI', 'Software Engineer & Cloud', name='research_field_enum')),
               nullable=True,
               postgresql_using="""CASE
                   WHEN interest_track IS NULL THEN NULL
                   WHEN interest_track ILIKE '%IoT%' OR interest_track ILIKE '%Embedded%' OR interest_track ILIKE '%Hardware%' THEN ARRAY['IoT Embedded'::research_field_enum]
                   WHEN interest_track ILIKE '%Software%' OR interest_track ILIKE '%Cloud%' OR interest_track ILIKE '%Web%' THEN ARRAY['Software Engineer & Cloud'::research_field_enum]
                   ELSE ARRAY['AI'::research_field_enum]
               END""")
    op.alter_column('registrations', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=postgresql.ENUM('Accepted', 'Pending', 'Rejected', name='selection_status_enum'),
               nullable=False,
               postgresql_using='status::selection_status_enum')
    op.alter_column('users', 'division',
               existing_type=sa.VARCHAR(length=100),
               type_=postgresql.ENUM('BPH', 'Akademik Riset', 'PSDM', 'Humas Multimedia', name='division_enum'),
               existing_nullable=False,
               postgresql_using='division::division_enum')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'division',
               existing_type=postgresql.ENUM('BPH', 'Akademik Riset', 'PSDM', 'Humas Multimedia', name='division_enum'),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('registrations', 'status',
               existing_type=postgresql.ENUM('Accepted', 'Pending', 'Rejected', name='selection_status_enum'),
               type_=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('registrations', 'interest_track',
               existing_type=postgresql.ARRAY(postgresql.ENUM('IoT Embedded', 'AI', 'Software Engineer & Cloud', name='research_field_enum')),
               type_=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('registrations', 'program_of_study',
               existing_type=postgresql.ENUM('S1 Informatika', 'S1 Sistem Informasi', 'S1 Sains Data', 'D3 Sistem Informasi', name='study_program_enum'),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('members', 'status',
               existing_type=postgresql.ENUM('Aktif', 'Tidak Aktif', 'Alumni', name='member_status_enum'),
               type_=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('members', 'interest_track',
               existing_type=postgresql.ARRAY(postgresql.ENUM('IoT Embedded', 'AI', 'Software Engineer & Cloud', name='research_field_enum')),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('members', 'role',
               existing_type=postgresql.ENUM('Ketua', 'Wakil Ketua', 'Kepala Divisi', 'Staff', 'Anggota', name='role_enum'),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('members', 'division',
               existing_type=postgresql.ENUM('BPH', 'Akademik Riset', 'PSDM', 'Humas Multimedia', name='division_enum'),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('members', 'program_of_study',
               existing_type=postgresql.ENUM('S1 Informatika', 'S1 Sistem Informasi', 'S1 Sains Data', 'D3 Sistem Informasi', name='study_program_enum'),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    sa.Enum('S1 Informatika', 'S1 Sistem Informasi', 'S1 Sains Data', 'D3 Sistem Informasi', name='study_program_enum').drop(op.get_bind())
    sa.Enum('BPH', 'Akademik Riset', 'PSDM', 'Humas Multimedia', name='division_enum').drop(op.get_bind())
    sa.Enum('Ketua', 'Wakil Ketua', 'Kepala Divisi', 'Staff', 'Anggota', name='role_enum').drop(op.get_bind())
    sa.Enum('IoT Embedded', 'AI', 'Software Engineer & Cloud', name='research_field_enum').drop(op.get_bind())
    sa.Enum('Aktif', 'Tidak Aktif', 'Alumni', name='member_status_enum').drop(op.get_bind())
    sa.Enum('Accepted', 'Pending', 'Rejected', name='selection_status_enum').drop(op.get_bind())
    # ### end Alembic commands ###
