"""refactor_photo_storage_columns

Revision ID: 2bf1f0a7a464
Revises: 695c97a3fbd8
Create Date: 2026-08-31 13:35:15.097670

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2bf1f0a7a464'
down_revision: str | Sequence[str] | None = '695c97a3fbd8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # Clean up any legacy base64 strings or oversized strings in existing records
    op.execute("UPDATE registrations SET photo = NULL WHERE photo IS NOT NULL AND LENGTH(photo) > 255")
    op.execute("UPDATE members SET avatar = NULL WHERE avatar IS NOT NULL AND LENGTH(avatar) > 255")
    op.execute("UPDATE users SET avatar = NULL WHERE avatar IS NOT NULL AND LENGTH(avatar) > 255")

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('members', 'avatar',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('registrations', 'photo',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('users', 'avatar',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'avatar',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('registrations', 'photo',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('members', 'avatar',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    # ### end Alembic commands ###
