"""add_full_member_columns

Revision ID: 3e4c86f31b7f
Revises: 5a3290fa6dab
Create Date: 2026-08-29 00:05:26.989012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e4c86f31b7f'
down_revision: Union[str, Sequence[str], None] = '5a3290fa6dab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('semester', sa.Integer(), nullable=True))
    op.add_column('members', sa.Column('domicile_city', sa.String(length=100), nullable=True))
    op.add_column('members', sa.Column('focus_expertise', sa.Text(), nullable=True))
    op.add_column('members', sa.Column('exploration_field', sa.Text(), nullable=True))
    op.add_column('members', sa.Column('field_reason', sa.Text(), nullable=True))
    op.add_column('members', sa.Column('programming_languages', sa.Text(), nullable=True))
    op.add_column('members', sa.Column('tools_frameworks', sa.Text(), nullable=True))
    op.add_column('members', sa.Column('project_experience', sa.Text(), nullable=True))
    op.add_column('members', sa.Column('hackathon_experience', sa.String(length=100), nullable=True))
    op.add_column('members', sa.Column('portfolio_url', sa.Text(), nullable=True))
    op.add_column('members', sa.Column('routine_commitment', sa.String(length=50), nullable=True))
    op.add_column('members', sa.Column('weekly_free_time', sa.String(length=50), nullable=True))
    op.add_column('members', sa.Column('other_activities', sa.Text(), nullable=True))
    op.add_column('members', sa.Column('discord_id', sa.String(length=100), nullable=True))
    op.add_column('members', sa.Column('registration_timestamp', sa.String(length=50), nullable=True))
    op.alter_column('members', 'interest_track',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('members', 'interest_track',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.drop_column('members', 'registration_timestamp')
    op.drop_column('members', 'discord_id')
    op.drop_column('members', 'other_activities')
    op.drop_column('members', 'weekly_free_time')
    op.drop_column('members', 'routine_commitment')
    op.drop_column('members', 'portfolio_url')
    op.drop_column('members', 'hackathon_experience')
    op.drop_column('members', 'project_experience')
    op.drop_column('members', 'tools_frameworks')
    op.drop_column('members', 'programming_languages')
    op.drop_column('members', 'field_reason')
    op.drop_column('members', 'exploration_field')
    op.drop_column('members', 'focus_expertise')
    op.drop_column('members', 'domicile_city')
    op.drop_column('members', 'semester')
    # ### end Alembic commands ###
