"""initial_schema_uuid7

Revision ID: 5a3290fa6dab
Revises: 
Create Date: 2026-08-28 23:39:49.366780

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '5a3290fa6dab'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
