"""make_division_optional

Revision ID: 695c97a3fbd8
Revises: 208840aa062f
Create Date: 2026-08-30 22:04:40.080505

"""
from collections.abc import Sequence

from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '695c97a3fbd8'
down_revision: str | Sequence[str] | None = '208840aa062f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('members', 'division',
               existing_type=postgresql.ENUM('BPH', 'Akademik Riset', 'PSDM', 'Humas Multimedia', name='division_enum'),
               nullable=True)
    op.alter_column('users', 'division',
               existing_type=postgresql.ENUM('BPH', 'Akademik Riset', 'PSDM', 'Humas Multimedia', name='division_enum'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'division',
               existing_type=postgresql.ENUM('BPH', 'Akademik Riset', 'PSDM', 'Humas Multimedia', name='division_enum'),
               nullable=False)
    op.alter_column('members', 'division',
               existing_type=postgresql.ENUM('BPH', 'Akademik Riset', 'PSDM', 'Humas Multimedia', name='division_enum'),
               nullable=False)
    # ### end Alembic commands ###
